# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/reference/configuration

[environments.bigquery]
url = "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=dsongcp-452504;"
user = ""
password = ""
validateMigrationNaming = true
schemas = ["dsongcp"]

[environments.bigquery.flyway]
locations = ["filesystem:./sql/bigquery"]

[environments.postgresql]
url = "jdbc:postgresql://localhost:5432/bts"
user = "postgres"
password = "postgres"

[environments.postgresql.flyway]
locations = ["filesystem:./sql/postgresql"]

[flyway]
cleanDisabled = false